# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b3f69b464aaf74118c11dd09b8cf942aff6d3d20423cf2e11c4ed83633510f9dadb511d0ebef9fe7056725b6e86a95e06e7b84632d9fd7d7b71c8f7e43264856

test:
  secret_key_base: 342f90e1bae589678337e587db60495790297e14191ac3b9deeee0cc3b8ffc527bc0a0dc334f8d9eeba87f8bfa98706ff04428ab2bc84e451d74f981677555eb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
